image: docker:latest
services:
- docker:dind

variables:
  DOCKER_DRIVER: overlay
  OPENSHIFT_SERVER: https://master.app.weadev.de:8443
  OPENSHIFT_DOMAIN: app.trasier.com
  DOCKER_REGISTRY: 172.30.232.187:5000

stages:
- build
- os-latest

.deploy: &deploy
  before_script:
  - oc login "$OPENSHIFT_SERVER" --token="$OPENSHIFT_TOKEN" --insecure-skip-tls-verify
  - oc project $OPENSHIFT_PROJECT 2> /dev/null --insecure-skip-tls-verify
  script:
  - "oc get services $APP 2> /dev/null || oc new-app . --name=$APP --strategy=docker"
  - "oc start-build $APP --from-dir=. --follow || sleep 3s || oc start-build $APP --from-dir=. --follow"
  - "oc get routes $APP 2> /dev/null || oc expose service $APP --hostname=$APP_HOST"

os-latest:
  <<: *deploy
  image: ayufan/openshift-cli
  stage: os-latest
  variables:
    OPENSHIFT_PROJECT: frankpfleger
    APP: booking
    APP_HOST: booking.$OPENSHIFT_DOMAIN
  environment:
    name: booking
    url: http://booking.$OPENSHIFT_DOMAIN
  only:
  - develop
